/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ResetPasswordTokenRouteImport } from './routes/reset-password.$token'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as AuthedReservationsRouteImport } from './routes/_authed/reservations'
import { Route as AuthedProfileRouteImport } from './routes/_authed/profile'
import { Route as AuthedDashboardRouteImport } from './routes/_authed/dashboard'
import { Route as AuthedAdminRouteImport } from './routes/_authed/admin'
import { Route as AuthedUnitsUnitIdRouteImport } from './routes/_authed/units.$unitId'
import { Route as AuthedUnitsUnitIdIndexRouteImport } from './routes/_authed/units.$unitId.index'
import { Route as AuthedUnitsUnitIdRoomsRoomIdRouteImport } from './routes/_authed/units.$unitId.rooms.$roomId'

const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordTokenRoute = ResetPasswordTokenRouteImport.update({
  id: '/reset-password/$token',
  path: '/reset-password/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedReservationsRoute = AuthedReservationsRouteImport.update({
  id: '/reservations',
  path: '/reservations',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedProfileRoute = AuthedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDashboardRoute = AuthedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAdminRoute = AuthedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedUnitsUnitIdRoute = AuthedUnitsUnitIdRouteImport.update({
  id: '/units/$unitId',
  path: '/units/$unitId',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedUnitsUnitIdIndexRoute = AuthedUnitsUnitIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedUnitsUnitIdRoute,
} as any)
const AuthedUnitsUnitIdRoomsRoomIdRoute =
  AuthedUnitsUnitIdRoomsRoomIdRouteImport.update({
    id: '/rooms/$roomId',
    path: '/rooms/$roomId',
    getParentRoute: () => AuthedUnitsUnitIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/register': typeof RegisterRoute
  '/signin': typeof SigninRoute
  '/admin': typeof AuthedAdminRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/profile': typeof AuthedProfileRoute
  '/reservations': typeof AuthedReservationsRoute
  '/invite/$token': typeof InviteTokenRoute
  '/reset-password/$token': typeof ResetPasswordTokenRoute
  '/units/$unitId': typeof AuthedUnitsUnitIdRouteWithChildren
  '/units/$unitId/': typeof AuthedUnitsUnitIdIndexRoute
  '/units/$unitId/rooms/$roomId': typeof AuthedUnitsUnitIdRoomsRoomIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/register': typeof RegisterRoute
  '/signin': typeof SigninRoute
  '/admin': typeof AuthedAdminRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/profile': typeof AuthedProfileRoute
  '/reservations': typeof AuthedReservationsRoute
  '/invite/$token': typeof InviteTokenRoute
  '/reset-password/$token': typeof ResetPasswordTokenRoute
  '/units/$unitId': typeof AuthedUnitsUnitIdIndexRoute
  '/units/$unitId/rooms/$roomId': typeof AuthedUnitsUnitIdRoomsRoomIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/register': typeof RegisterRoute
  '/signin': typeof SigninRoute
  '/_authed/admin': typeof AuthedAdminRoute
  '/_authed/dashboard': typeof AuthedDashboardRoute
  '/_authed/profile': typeof AuthedProfileRoute
  '/_authed/reservations': typeof AuthedReservationsRoute
  '/invite/$token': typeof InviteTokenRoute
  '/reset-password/$token': typeof ResetPasswordTokenRoute
  '/_authed/units/$unitId': typeof AuthedUnitsUnitIdRouteWithChildren
  '/_authed/units/$unitId/': typeof AuthedUnitsUnitIdIndexRoute
  '/_authed/units/$unitId/rooms/$roomId': typeof AuthedUnitsUnitIdRoomsRoomIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/register'
    | '/signin'
    | '/admin'
    | '/dashboard'
    | '/profile'
    | '/reservations'
    | '/invite/$token'
    | '/reset-password/$token'
    | '/units/$unitId'
    | '/units/$unitId/'
    | '/units/$unitId/rooms/$roomId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/register'
    | '/signin'
    | '/admin'
    | '/dashboard'
    | '/profile'
    | '/reservations'
    | '/invite/$token'
    | '/reset-password/$token'
    | '/units/$unitId'
    | '/units/$unitId/rooms/$roomId'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/forgot-password'
    | '/register'
    | '/signin'
    | '/_authed/admin'
    | '/_authed/dashboard'
    | '/_authed/profile'
    | '/_authed/reservations'
    | '/invite/$token'
    | '/reset-password/$token'
    | '/_authed/units/$unitId'
    | '/_authed/units/$unitId/'
    | '/_authed/units/$unitId/rooms/$roomId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  RegisterRoute: typeof RegisterRoute
  SigninRoute: typeof SigninRoute
  InviteTokenRoute: typeof InviteTokenRoute
  ResetPasswordTokenRoute: typeof ResetPasswordTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password/$token': {
      id: '/reset-password/$token'
      path: '/reset-password/$token'
      fullPath: '/reset-password/$token'
      preLoaderRoute: typeof ResetPasswordTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/reservations': {
      id: '/_authed/reservations'
      path: '/reservations'
      fullPath: '/reservations'
      preLoaderRoute: typeof AuthedReservationsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/profile': {
      id: '/_authed/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthedProfileRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/dashboard': {
      id: '/_authed/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthedDashboardRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/admin': {
      id: '/_authed/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthedAdminRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/units/$unitId': {
      id: '/_authed/units/$unitId'
      path: '/units/$unitId'
      fullPath: '/units/$unitId'
      preLoaderRoute: typeof AuthedUnitsUnitIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/units/$unitId/': {
      id: '/_authed/units/$unitId/'
      path: '/'
      fullPath: '/units/$unitId/'
      preLoaderRoute: typeof AuthedUnitsUnitIdIndexRouteImport
      parentRoute: typeof AuthedUnitsUnitIdRoute
    }
    '/_authed/units/$unitId/rooms/$roomId': {
      id: '/_authed/units/$unitId/rooms/$roomId'
      path: '/rooms/$roomId'
      fullPath: '/units/$unitId/rooms/$roomId'
      preLoaderRoute: typeof AuthedUnitsUnitIdRoomsRoomIdRouteImport
      parentRoute: typeof AuthedUnitsUnitIdRoute
    }
  }
}

interface AuthedUnitsUnitIdRouteChildren {
  AuthedUnitsUnitIdIndexRoute: typeof AuthedUnitsUnitIdIndexRoute
  AuthedUnitsUnitIdRoomsRoomIdRoute: typeof AuthedUnitsUnitIdRoomsRoomIdRoute
}

const AuthedUnitsUnitIdRouteChildren: AuthedUnitsUnitIdRouteChildren = {
  AuthedUnitsUnitIdIndexRoute: AuthedUnitsUnitIdIndexRoute,
  AuthedUnitsUnitIdRoomsRoomIdRoute: AuthedUnitsUnitIdRoomsRoomIdRoute,
}

const AuthedUnitsUnitIdRouteWithChildren =
  AuthedUnitsUnitIdRoute._addFileChildren(AuthedUnitsUnitIdRouteChildren)

interface AuthedRouteChildren {
  AuthedAdminRoute: typeof AuthedAdminRoute
  AuthedDashboardRoute: typeof AuthedDashboardRoute
  AuthedProfileRoute: typeof AuthedProfileRoute
  AuthedReservationsRoute: typeof AuthedReservationsRoute
  AuthedUnitsUnitIdRoute: typeof AuthedUnitsUnitIdRouteWithChildren
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedAdminRoute: AuthedAdminRoute,
  AuthedDashboardRoute: AuthedDashboardRoute,
  AuthedProfileRoute: AuthedProfileRoute,
  AuthedReservationsRoute: AuthedReservationsRoute,
  AuthedUnitsUnitIdRoute: AuthedUnitsUnitIdRouteWithChildren,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  RegisterRoute: RegisterRoute,
  SigninRoute: SigninRoute,
  InviteTokenRoute: InviteTokenRoute,
  ResetPasswordTokenRoute: ResetPasswordTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
